# Generated by Django 4.2.7 on 2023-11-17 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_cliente_producto_perfilusuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
